# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - name: Nexus IQ for GitHub Actions
        # You may pin to the exact commit or the version.
        # uses: sonatype-nexus-community/iq-github-action@ef2fae57de0888b50cedf3c9e1c2886bf3e5f21a
        uses: sonatype-nexus-community/iq-github-action@1.1.1
        with:
          # Nexus IQ Server URL
          serverUrl: https://iq.bbarbosa.eu.ngrok.io/
          # Username to connect to IQ Server for policy evaluation
          username: admin
          # Password to connect to IQ Server for policy evaluation
          password: 01021994
          # Determines the policy elements (policies, labels, and license threat groups) to associate with this build, and is managed via the Nexus IQ Server.
          applicationId: NodeGoat__bcbarbosa
          # Controls the stage the policy evaluation will be run against on the Nexus IQ Server.
          stage: stage-release
          # This is the path to a specific application archive file, a directory containing such archives or the ID of a Docker image. For archives, a number of formats are supported, including jar, war, ear, tar, tar.gz, zip and many others.
          target: .

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
